from pathlib import Path
path = Path('/home/ubuntu/nihongo-video-hub/client/src/pages/Home.tsx')
text = path.read_text()
text = text.replace('import { Button } from "@/components/ui/button";\n', 'import { Button } from "@/components/ui/button";\nimport { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";\n')
text = text.replace('type Topic = "文法" | "單字" | "聽解" | "讀解" | "綜合";\n', 'type Topic = "文法" | "單字" | "聽解" | "讀解" | "綜合";\ntype StudyMode = "videos" | "songs";\n')
text = text.replace('  const [activeLevel, setActiveLevel] = useState<Level>("N5");\n', '  const [activeStudyMode, setActiveStudyMode] = useState<StudyMode>("videos");\n  const [activeLevel, setActiveLevel] = useState<Level>("N5");\n')
text = text.replace('          <div className="hidden items-center gap-3 md:flex">\n            <a href="#catalog" className="border border-[#21392f]/30 bg-[#f8f0de]/80 px-4 py-2 text-sm font-semibold tracking-wide shadow-[3px_3px_0_#21392f] transition hover:-translate-y-0.5">影片月台</a>\n            <a href="#songs" className="border border-[#21392f]/30 bg-[#f8f0de]/80 px-4 py-2 text-sm font-semibold tracking-wide shadow-[3px_3px_0_#b7442e] transition hover:-translate-y-0.5">日文歌曲</a>\n          </div>', '          <div className="hidden items-center gap-3 md:flex">\n            <a href="#study-switch" onClick={() => setActiveStudyMode("videos")} className="border border-[#21392f]/30 bg-[#f8f0de]/80 px-4 py-2 text-sm font-semibold tracking-wide shadow-[3px_3px_0_#21392f] transition hover:-translate-y-0.5">影片學習</a>\n            <a href="#study-switch" onClick={() => setActiveStudyMode("songs")} className="border border-[#21392f]/30 bg-[#f8f0de]/80 px-4 py-2 text-sm font-semibold tracking-wide shadow-[3px_3px_0_#b7442e] transition hover:-translate-y-0.5">日文歌曲</a>\n          </div>')
text = text.replace('              <a href="#catalog">\n                <Button className="h-12 rounded-none bg-[#21392f] px-7 text-base font-bold text-[#fff7e6] shadow-[5px_5px_0_#b7442e] transition hover:-translate-y-1 hover:bg-[#2f5d46]">\n                  開始查詢路線\n                </Button>\n              </a>\n              <a href="#songs" className="inline-flex h-12 items-center justify-center border border-[#21392f]/30 bg-[#f8f0de] px-7 text-base font-bold text-[#21392f] shadow-[5px_5px_0_#24628f] transition hover:-translate-y-1">\n                查看日文歌曲\n              </a>', '              <a href="#study-switch" onClick={() => setActiveStudyMode("videos")}>\n                <Button className="h-12 rounded-none bg-[#21392f] px-7 text-base font-bold text-[#fff7e6] shadow-[5px_5px_0_#b7442e] transition hover:-translate-y-1 hover:bg-[#2f5d46]">\n                  開始影片學習\n                </Button>\n              </a>\n              <a href="#study-switch" onClick={() => setActiveStudyMode("songs")} className="inline-flex h-12 items-center justify-center border border-[#21392f]/30 bg-[#f8f0de] px-7 text-base font-bold text-[#21392f] shadow-[5px_5px_0_#24628f] transition hover:-translate-y-1">\n                用日文歌曲學習\n              </a>')
insert = '''\n\n      <section id="study-switch" className="relative border-b border-[#21392f]/15 bg-[#fff8e9] px-5 py-8 md:px-10 lg:px-16">\n        <div className="mx-auto grid max-w-7xl gap-5 lg:grid-cols-[0.85fr_1.15fr] lg:items-center">\n          <div>\n            <p className="text-xs font-black uppercase tracking-[0.28em] text-[#b7442e]">Choose Your Platform</p>\n            <h2 className="mt-2 font-serif text-3xl font-black tracking-[-0.03em] text-[#21392f] md:text-4xl">今天想怎麼學日文？</h2>\n            <p className="mt-3 text-sm leading-6 text-[#314a40] md:text-base">先選學習方式，再進入對應內容；手機上不需要一路滑到底，也不會一次看到太多分類按鈕。</p>\n          </div>\n          <Tabs value={activeStudyMode} onValueChange={(value) => setActiveStudyMode(value as StudyMode)} className="w-full">\n            <TabsList className="grid h-auto w-full grid-cols-1 gap-3 rounded-none bg-transparent p-0 sm:grid-cols-2">\n              <TabsTrigger value="videos" className="min-h-24 rounded-none border-2 border-[#21392f] bg-[#f8f0de] p-4 text-left shadow-[6px_6px_0_#21392f] data-[state=active]:bg-[#21392f] data-[state=active]:text-[#fff7e6]">\n                <span className="flex w-full items-start gap-3">\n                  <Video className="mt-1 h-5 w-5 shrink-0" />\n                  <span>\n                    <span className="block text-lg font-black">影片學習</span>\n                    <span className="mt-1 block text-sm font-medium leading-5 opacity-80">依 JLPT 級別與主題找教學影片。</span>\n                  </span>\n                </span>\n              </TabsTrigger>\n              <TabsTrigger value="songs" className="min-h-24 rounded-none border-2 border-[#b7442e] bg-[#f8f0de] p-4 text-left shadow-[6px_6px_0_#b7442e] data-[state=active]:bg-[#b7442e] data-[state=active]:text-[#fff7e6]">\n                <span className="flex w-full items-start gap-3">\n                  <Music2 className="mt-1 h-5 w-5 shrink-0" />\n                  <span>\n                    <span className="block text-lg font-black">日文歌曲</span>\n                    <span className="mt-1 block text-sm font-medium leading-5 opacity-80">用歌曲練聽力、單字與語感。</span>\n                  </span>\n                </span>\n              </TabsTrigger>\n            </TabsList>\n          </Tabs>\n        </div>\n      </section>'''
text = text.replace('      </section>\n\n      <section id="catalog"', '      </section>' + insert + '\n\n      {activeStudyMode === "videos" ? (\n      <section id="catalog"')
text = text.replace('      </section>\n\n\n      <section id="songs"', '      </section>\n      ) : null}\n\n\n      {activeStudyMode === "songs" ? (\n      <section id="songs"')
text = text.replace('      </section>\n\n      <footer', '      </section>\n      ) : null}\n\n      <footer', 1)
text = text.replace('            <aside className="relative">', '            <aside className="relative hidden lg:block">')
mobile_panel = '''\n          <div className="mb-8 border-2 border-[#21392f] bg-[#fff7e6] p-4 shadow-[7px_7px_0_#24628f] lg:hidden">\n            <p className="mb-4 text-sm font-black tracking-[0.18em] text-[#b7442e]">快速篩選影片</p>\n            <div className="grid gap-4 sm:grid-cols-2">\n              <label className="block">\n                <span className="mb-2 block text-xs font-black uppercase tracking-[0.18em] text-[#314a40]/80">JLPT 級別</span>\n                <select\n                  value={activeLevel}\n                  onChange={(event) => switchLevel(event.target.value as Level)}\n                  className="h-12 w-full rounded-none border-2 border-[#21392f]/30 bg-[#f8f0de] px-4 text-base font-black text-[#21392f] outline-none focus:border-[#b7442e]"\n                >\n                  {levels.map((item) => (\n                    <option key={item.level} value={item.level}>{item.level}｜{item.label}（{countsByLevel[item.level]} 支）</option>\n                  ))}\n                </select>\n              </label>\n              <label className="block">\n                <span className="mb-2 block text-xs font-black uppercase tracking-[0.18em] text-[#314a40]/80">主題</span>\n                <select\n                  value={activeTopic}\n                  onChange={(event) => switchTopic(event.target.value as \"全部\" | Topic)}\n                  className="h-12 w-full rounded-none border-2 border-[#21392f]/30 bg-[#f8f0de] px-4 text-base font-black text-[#21392f] outline-none focus:border-[#b7442e]"\n                >\n                  {topics.map((topic) => (\n                    <option key={topic} value={topic}>{topic === \"全部\" ? \"全部主題\" : topic}</option>\n                  ))}\n                </select>\n              </label>\n            </div>\n            <p className="mt-4 border-t border-[#21392f]/15 pt-3 text-sm font-bold text-[#314a40]">目前顯示 {activeLevel}・{activeTopic === \"全部\" ? \"全部主題\" : activeTopic}，共 {filteredVideos.length} 支影片。</p>\n          </div>\n'''
text = text.replace('          <div className="grid gap-10 lg:grid-cols-[320px_1fr]">', mobile_panel + '\n          <div className="grid gap-10 lg:grid-cols-[320px_1fr]">')
text = text.replace('              <div className="flex flex-wrap gap-2">\n                {topics.map((topic) => (', '              <div className="hidden flex-wrap gap-2 sm:flex">\n                {topics.map((topic) => (')
path.write_text(text)
